### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by HappyDay-design** [IChihWang/Roadrunner#1]
Thank you very much
I had an error when running python main.py
Traceback (most recent call last):
  File "/home/osboxes/Desktop/Roadrunner/main.py", line 135, in <module>
    seed = int(sys.argv[2])
IndexError: list index out of range

**Comment by IChihWang** [comment]
Hi TrinhTuanHung,

You might need to specify the argv's when running the main.py, according to:
"Usage: python main.py <arrival_rate (0~1.0)> <seed> <schedular> <is_slowdown_control T/F>"

For example: $ python main.py 0.5 0 0 T
For arrival rate = 0.5, random seed = 0, scheduler = 0 (This can refer to IntersectionManager.py), and T for slowdown control for cars on the road segment.

**Comment by HappyDay-design** [comment]
Thank you very much for your quick reply

**Comment by HappyDay-design** [comment]
Hello.
I saw that your paper has been published. [https://dl.acm.org/doi/abs/10.1145/3488246](url)
But I can not download it. Could you please upload your paper to this repo?
Thank you very much!

**Comment by IChihWang** [comment]
Hi TrinhTunanHung,
I would like to, but I cannot upload my paper here.
When I submit the paper to ACM, the copyright of the paper has been transferred to them.
You might need to contact libraries or universities which have access to ACM to get the full copy of the paper.

**Comment by HappyDay-design** [comment]
> Hi TrinhTunanHung, I would like to, but I cannot upload my paper here. When I submit the paper to ACM, the copyright of the paper has been transferred to them. You might need to contact libraries or universities which have access to ACM to get the full copy of the paper.

Thank you very much for replying to me!
